Add sponsorship policy. [WIP]
NixOS/foundation pull request #128
Opened 2024-03-29 22:07 UTC by djacu

Fixes #110.

Formally submitting this as I think it is a sufficiently good place to start.

- Taken from @piegamesde's and @tomberek's input in the related issue.
- Modified to improve spelling and grammar.
- Wasn't sure how to parse the "and should be a home page or content related" phrase so I removed it.
- Changed line numbers so it formats in Markdown nicely.

2024-03-29 22:25 UTC, tomberek commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, including the event organizers and the Foundation Board.
```suggestion
    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
```
perhaps clearer?

2024-03-30 20:58 UTC, piegamesde commented
This sponsorship policy formalizes the status quo of our current procedures fairly well. Or in other words, I fail how to see how it would help preventing any situations like the one we found ourselves in for this NixCon NA.

I mean, if your goal is "having a sponsorship policy at all", then sure, it's fine, go ahead. But if your goal is to actually do something to improve the situation by the means of creating a sponsorship policy and to prevent bad situation in the future, then that goal will not be reached.

To be blunt: To me, this text is almost useless and completely disregards most of the discussion points we have had on this topic. And I am increasingly bitter about the time and energy I lost on debating this since clearly nobody is listening.

2024-03-30 21:29 UTC, paperdigits commented
> To me, this text is almost useless and completely disregards most of the discussion points we have had on this topic. And I am increasingly bitter about the time and energy I lost on debating this since clearly nobody is listening.

Please submit your own sponsorship policy such that we can formally read and understand exactly what is desired; please be take action, rather than have a reaction. That's the only way we'll get anywhere.

2024-03-30 21:44 UTC, Janik-Haag commented
> Please submit your own sponsorship policy such that we can formally read and understand exactly what is desired

they did ... https://github.com/NixOS/foundation/issues/110#issuecomment-2006874249

2024-03-30 21:47 UTC, paperdigits commented
That's certainly a draft, where is the more concrete, flushed out text?

2024-03-30 21:50 UTC, piegamesde commented
@paperdigits would you prefer ignoring a finalized version of my text over ignoring my drafts? Should I paste what I wrote into a pretty PR for you to take it seriously?

2024-03-30 21:54 UTC, paperdigits commented
I find your patronizing tone very off putting, @piegamesde, I'd ask that we maintain a civil tone and stay on topic. 

While your draft is good, the bits such as "3.4. If want to rule out certain kinds of companies out of principle, put that here" and "5.3. Insert the rest of https://discourse.nixos.org/t/nixcon-na-2024-is-getting-sponsored-by-anduril-what-to-do-about-it/41258/17. This could be fleshed out in here or somewhere else, should there be a better place to write these down" compose quite a bit of the difficult bits that are being discussed. Without those bits filled in, it's more difficult to reach a final consensus. 

It doesn't need to be a PR per se, but something that doesn't have "fill me in" parts would be really helpful.

2024-04-01 11:25 UTC, zimbatm commented
Thanks @djacu 

> This sponsorship policy formalizes the status quo of our current procedures fairly well. Or in other words, I fail how to see how it would help preventing any situations like the one we found ourselves in for this NixCon NA.

@paperdigits, please take some time to read your comments and consider how your feedback could be applied to yourself. Constructive feedback would try to address Piegame's core concern instead of redirecting.

Both proposals also have a similar hole where the composition of the selection committee is left open for interpretation.

>  3. Objections should be specific to the sponsor and cite relevant reasons why the sponsorship would impede the NixOS mission.

@piegamesde under that rule, I believe we could discard some sponsors on the grounds that they are too controversial. The amount of focus we lost on that topic is already considerable, and it is good grounds for future discards.

That said, the current policy requires 2 objections, and it's unclear if that would only count as a single objection. Or if the same objection can come from two members. What did you have in mind @djacu ?

2024-04-01 14:38 UTC, piegamesde requested changes

2024-04-01 14:38 UTC, piegamesde commented on Sponsorship.md
> +Nonetheless, the Foundation retains the right to decline sponsorship through a Board vote in cases where it would impede the Foundation's mission.
```suggestion
This policy is also established to protect the NixOS project from bad publicity which may occur because of sponsorships.
Therefore, the Foundation retains the right to decline sponsorship through a Board vote in cases where it would impede the Foundation's mission.
```

This is why we are doing all of this in the first place, so let's be frank about it.

2024-04-01 14:38 UTC, piegamesde commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
```suggestion
    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, which is composed of the event organizers, the Foundation Board, the marketing team and the moderation team.
```

2024-04-01 14:38 UTC, piegamesde commented on Sponsorship.md
> +    2. Selection Committee members shall be notified at least 2 weeks prior to the event and provided with at least 1 week to submit objections to the Foundation Board via email.
Why submit objections to the Foundation Board instead of the sponsorship chair, especially since the Foundation Board essentially *is* the Selection Committee?

2024-04-01 14:38 UTC, piegamesde commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
```suggestion
    If at least one team of which the selection committee is composed of raises objections for a sponsor, then these objections must be discussed with the selection committee. If after that discussion the objection is not retracted, then the sponsor has to be declined. 
```

Some general thoughts about this

- I think it is better to think in terms of teams as units with their own internal decision making process rather than of its individual members
- I think that declaring voting mechanisms in such detail may not be necessary; I'd like to avoid over-specifying procedures where possible. Moreover, I'd prefer a veto-based mechanism with lazy consensus over a voting-based mechanism.

2024-04-01 14:43 UTC, piegamesde commented
@paperdigits apologies for my tone.

Of the two placeholder points you remark, I have basically given up on both of them, so consider them removed. At this point, I think it is easier for me to focus on adding the points I care most about back into this proposal instead of polishing my own draft further.

2024-04-01 17:53 UTC, zimbatm commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
I like this. One concern is how much overhead this new process will add. Organizing a conference is already hard enough, especially with all the timings. So keeping this to a minimum would be helpful. In that spirit, having the foundation involved means the overhead for decision-making can be reduced.

2024-04-02 05:04 UTC, tomberek commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
@piegamesde What is the rationale to include each of these in selection committee?
- Marketing?
- Moderation?

The clearest rationale given was by uninsange: "per its duty, the Moderation team is necessarily exposed to a fairly diverse sampling of the NixOS community". I'm going to reject this; they are exposed to the most divisive sampling of the community, and there is plenty of precedent that Moderation teams should not involve themselves in contentious topics while moderating due to conflicts of interest. [Example](https://rust-lang.github.io/rfcs/1068-rust-governance.html?highlight=moderation#moderation-team)

I don't see why Marketing should have a veto (disclaimer: I am on the Marketing team). While we may have some insight into the broader public sentiment, I would not want to claim this is strong enough to mean we know better than a local event team. I am extremely hesitant to claim that we have some special insight into the acceptable morals+ethics that should give us a veto.

The more groups that are involved leads to more discussion and debate. The Moderation Team has decided that its decisions are not up for public debate; people should contact the team directly or use a few limited channels to engage in a civil manner. I don't think the event teams should declare a similar policy, but why shouldn't they?  Why should only the event teams be subject to veto by other teams? Will each official team's decisions be up for review/debate/veto by other teams? Will Moderation establish a similar set of transparency policies and allow a veto other teams to oversee their actions? This way leads to madness and division. We are establishing a precedent for how our organization is run. I've looked around and talked to many other communities - I spent an entire day at SCALE talking to a wide array of communities about their policies - and I've not found a single example of such a veto being given to a Moderation nor a Marketing team.

(@zimbatm and others) I was quite impressed with how Postgres handles their community (https://momjian.us/main/blogs/pgblog/2023.html#September_11_2023). Their approach is to ensure transparency, make sure people are not tricked, but otherwise let the teams do their work. Please read through their approach and [policies](https://www.postgresql.org/about/policies/) - and consider if we should adopt this general approach to our community organization.

2024-04-02 23:46 UTC, RaitoBezarius commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
I will be opinionated because I'm running out of energy, I will speak for myself as a member of the project lead team of NixCon, but I am not comfortable any future NixCon calling themselves as such if they don't have the **moderation team** in their **selection committee** given the current circumstances that made us discuss all of this.

You can interpret this as my own veto as a PL member. As NixCon are the most important events that the Foundation organize, this sponsorship policy is most likely related to NixCons, obviously, someone can use another name and desire to do adopt another policy with another PL team. I would dare to say this would not be an effective way to evade my prior "highly suggested" recommendation on having the moderation team.

If the moderation team is not part of the decision-making, it's highly likely that the next mistake will engulf again the community and will cause many strained folks in the ecosystem. Thus, I don't see how any large, serious event with sponsorship can escape from having the moderation team in the loop as stakeholders.

If the moderation team is deemed problematic, that's a problem for another venue, albeit it's related to this one. We should be frank on this too, if some folks believe the moderation team to be problematic, they should raise it appropriately (read: not like some folks did in the days surrounding the situation that created the need for this document), ultimately, if there's a need to replace the moderation team, that shall be done with the consequences this can bear with respect to the community trust and the active contributors can decide for themselves whether they want to spend their free time in such an ecosystem after all decisions are done. Sorry to be brutal, but I hate going around in circles.

2024-04-03 03:09 UTC, djacu commented
> That said, the current policy requires 2 objections, and it's unclear if that would only count as a single objection. Or if the same objection can come from two members. What did you have in mind @djacu ?

Well that was taken from the issue. But my thoughts were that two separate members would need to bring up the objection. Similar to a motion on a council where one person brings up a motion and a second votes to carry the motion forward. Except here it would be simply two votes.

2024-04-03 03:14 UTC, djacu commented
> However, I'd like to see 5.2 "Employees of rejected companies must be welcomed as community members in the community and at events, as long as they drop all public affiliation with their employer within these spaces." incorporated into this proposal in some way or another.

I am good with the first half of 5.2 but the second half is a bit ambiguous. To what degree would they have to drop all public affiliation?

- Not having their company on their badge (if that is a thing)?
- Not wearing apparel from their company?
- Not mentioning their company if they give a talk? E.g. "Hello, my name is X and I work for company Y."

Any of these seem a little too much to put on the individual.

2024-04-03 06:56 UTC, thufschmitt commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
This was already discussed during the open board call, and we agreed to have both the moderation and the marketing team in here for a first version. Everyone is welcome to re-discuss it, but _after_ we have this first iteration.

2024-04-03 06:56 UTC, thufschmitt commented on Sponsorship.md
> +    2. Selection Committee members shall be notified at least 2 weeks prior to the event and provided with at least 1 week to submit objections to the Foundation Board via email.
A practical reason in that there's no way to reach out to the committee in general, while there's an email address to the foundation.
I'm fine with relaxing it if it doesn't make thing s too ambiguous:

```suggestion
    2. Selection Committee members shall be notified at least 2 weeks prior to the event and provided with at least 1 week to submit objections to committee members in written form.
```

2024-04-03 13:45 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/update-on-sponsorship-policy-discussion/42704/1

2024-04-03 16:51 UTC, refroni commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
Would it be within scope for this document to also mention what is within the scope/"What counts as" a formal NixOS event?

2024-04-03 17:10 UTC, djacu commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
I disagree with this change:

- Allowing objections from individual teams without a clear threshold for validity could open the door for manipulation or strategic objections aimed at excluding certain sponsors for reasons unrelated to the sponsor's suitability.
- With the suggested changes, it would only require that one team raise an objection and refuse to retract it.

2024-04-03 17:45 UTC, numinit commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
I agree with @djacu. This policy should seek to minimize the possibility of any under the table decisions coming from _any_ team. From an outsider perspective, the moderation team has a lot of influence. Using community outrage as a proxy for decisionmaking is a sure way to remove any illusion that a decision was made neutrally.

2024-04-03 17:49 UTC, numinit commented on Sponsorship.md
> +Nonetheless, the Foundation retains the right to decline sponsorship through a Board vote in cases where it would impede the Foundation's mission.
Under the table decisions in the name of "protecting the NixOS project" will be more embarrassing to find out than any potential damage a sponsor could do.

2024-04-03 18:23 UTC, paperdigits commented on Sponsorship.md
> +    2. Selection Committee members shall be notified at least 2 weeks prior to the event and provided with at least 1 week to submit objections to the Foundation Board via email.
> 2. Selection Committee members shall be notified at least 2 weeks prior to the event and provided with at least 1 week to submit objections to the Foundation Board via email.

So if a person in the community who is not part of selection committee wants to weigh in on a sponsor or potential sponsor, how would that be done? 

Right now it seems like the prevailing perception is that the moderation team will raise concerns on behalf of the community. But the decision making on what constitutes raising an objection is not documented. And the decision making for each team is also not a documented process and should be left opaquely up to each team?

2024-04-03 18:31 UTC, zimbatm commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
I like @piegamesde's approach better, as it leaves more room for conversation. Ideally, the decision is also put in context with the funds we need to run the event, what sponsors have become available, and how it fits with the NixCon brand.

We can always adjust the policy if any issues come from it.

2024-04-03 18:37 UTC, djacu commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
It appears imperative to convene another meeting to delve into several pertinent matters that remain open for discussion. Specifically, we should address:

- Fine-tuning our word choices to ensure precision and clarity.
- The criteria for selecting the sponsor chair.
- Establishing a protocol for resolving objections effectively.
- Implementing mechanisms for transparently documenting objections.
- Reassessing the composition of teams/groups comprising the selection committee.

By addressing these points, we can ensure a more comprehensive understanding and facilitate smoother decision-making processes.

2024-04-03 18:47 UTC, numinit commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
The main concern I have to keep that trust is avoiding accidental "black box" decision-making on this stuff. We go to some serious efforts for full transparency with nixpkgs itself. I think our community taking the same approach is a good direction, and to that end the policy ought to be "boring." If any questions arise about a sponsor, we just go through the checklist, and it's plausible (based on the design of the rules) that no one had conflicts of interest at any step.

2024-04-03 18:54 UTC, crertel commented
I'm just somebody quietly using Nix over in the corner and reading [some of the work on this problem](https://github.com/NixOS/foundation/issues/110), but I'm not comfortable with a de-facto power grab by the moderation team here for vetoing events and then enforcing opinions on whether or not somebody can freely associate themselves with their employers at an event.

This is extremely unusual from everything I've seen at industry conferences, and the one time I recall it happening (over in the Elixir community) we still make fun of everybody involved in that decision and the awkwardness it caused.

I'll also point out that, as written, it seems that _any_ rejected sponsorship would mean you couldn't fly your flag--for example, if I had some small business whose proposed sponsorship is of too little value to handle and got rejected this proposed change would mean I couldn't wear my company T-shirt. That seems dumb.

---

Taking a step back though, I think y'all are overthinking this and making mountains out of molehills. It's hard enough to get events organized and _harder still_ to get funding for those events. Maybe just focus on getting a few years of events with sponsorship up reliably, assume good faith from everyone involved, don't overindex on what _might_ happen with a sponsor that some people _might_ not approve of, and then check in to see if anything needs to be changed if you can do that without goofing up a few times in a row at scale.

I _guarantee_ that the handwringing over theoretical bad PR or whatever is a distraction from the already hard work of setting up events and getting paid. Few people know about Nix at all outside of a few corners of tech, fewer people still are actually running it meaningfully in production, even fewer of those are doing so for companies.

The ugly but reassuring truth is "basically _nobody cares_ in the world at large." Take refuge in that, go outside and touch grass, and maybe consider removing roadblocks to sponsorship and avoiding adding processes that allow subsets of the ecosystem not doing the work to make it harder for those actually doing it.

2024-04-03 19:13 UTC, djacu commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
> I like @piegamesde's approach better, as it leaves more room for conversation. Ideally, the decision is also put in context with the funds we need to run the event, what sponsors have become available, and how it fits with the NixCon brand.
> 
> We can always adjust the policy if any issues come from it. In general, we should operate on the basis of trust.

Section 4.4 addresses resolution rather than conversation. The policy does not explicitly outline guidelines for conversation, as it is deemed appropriate for the selection committee/teams to determine. Given its role as the final authoritative decision, it should be crafted to minimize potential biases, partiality, and manipulation.

2024-04-03 20:02 UTC, RaitoBezarius commented
> I'm just somebody quietly using Nix over in the corner and reading [some of the work on this problem](https://github.com/NixOS/foundation/issues/110), but I'm not comfortable with a de-facto power grab by the moderation team here for vetoing events and then enforcing opinions on whether or not somebody can freely associate themselves with their employers at an event.
> [...]
> The ugly but reassuring truth is "basically _nobody cares_ in the world at large." Take refuge in that, go outside and touch grass, and maybe consider removing roadblocks to sponsorship and avoiding adding processes that allow subsets of the ecosystem not doing the work to make it harder for those actually doing it.

Thank you for your comment, it is just sad that your comment contains so much contempt and seems to discard the possibility that what happened had real effects on people over the past months. I recommend taking the time to review the existing discourse to avoid writing a message which seems to be ignoring all the feelings of people working on the matter and pouring their soul in this thing for the past days. Furthermore, I recommend also to forego to suggest that it's sufficient "to touch the grass" for problems to disappear in a community.

2024-04-03 20:09 UTC, RaitoBezarius commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
We can pass a first chunk of policy without resolving all the first points except the composition of teams/groups compromising the selection committee.

We could technically even do it in multiple steps, let the selection committee undefined, pass the rest of the text, then work on the definition of the selection committee, etc.

Furthermore, we have two/three ways to proceed about that:
(a) We schedule a meeting urgently and try to involve the folks participating in that discussion, ideally before next Tuesday.
(b) We resolve between ourselves the remaining objections before next Tuesday ideally
(c) We make the Foundation board resolve the remaining objections

If people want (a), I would like to know it quickly and if we cannot get this meeting going before next Tuesday, we should carefully consider (b) or (c) and if we really cannot consider it, I can post to postpone again the decision in the next 2 weeks or by the next week if we do exceptionally a board meeting to decide.

> @refroni Would it be within scope for this document to also mention what is within the scope/"What counts as" a formal NixOS event?

I would personally put it like this: any event with a large audience (>= 50/100) that uses the Nix brand.

We can weaken, for starters, by saying: any event with a large audience that has a financial relationship with the NixOS Foundation.

2024-04-03 20:36 UTC, crertel commented
> Thank you for your comment, it is just sad that your comment contains so much contempt and seems to discard the possibility that what happened had real effects on people over the past months. I recommend taking the time to review the existing discourse to avoid writing a message which seems to be ignoring all the feelings of people working on the matter and pouring their soul in this thing for the past days.
> [...]
> Furthermore, I recommend also to forego suggestions that it's sufficient "to touch the grass" for problems to disappear in a community.

You have not commented on the substance of the comment:

* This is a defacto power grab.
* Similarly draconian measures are uncommon and have not worked out in the past for other communities and events.
* Nix is quite small right now in the grand scheme of things so we have room to assume positive intent and focus on getting _any_ event up.
* The existence of emotional investment and long discourse and debate should not be conflated with the concrete problems of getting any event going with any amount of sponsorship from any group.

2024-04-03 20:37 UTC, AshleyYakeley commented
> I'm not comfortable with a de-facto power grab by the moderation team here for vetoing events and then enforcing opinions on whether or not somebody can freely associate themselves with their employers at an event.

I agree with this. The rationale given is that the moderation team somehow represents the community? But I think it's the other way around: as an inevitable consequence of moderation, the moderation team has a great deal of influence over what counts as "the community" and who may participate in it. This isn't a bad thing, moderation needs to be done, but we should recognise that the community has no reciprocal influence over the moderation team, and so the latter should not be considered representative of the former.

2024-04-03 21:30 UTC, djacu commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
> We can pass a first chunk of policy without resolving all the first points except the composition of teams/groups compromising the selection committee.
> 
> We could technically even do it in multiple steps, let the selection committee undefined, pass the rest of the text, then work on the definition of the selection committee, etc.

While I agree with the approach of passing the core aspects of the policy first and addressing other points subsequently, I share a concern regarding potential loss of momentum if we delay resolution on certain elements.

> (a) We schedule a meeting urgently and try to involve the folks participating in that discussion, ideally before next Tuesday.

Could you provide further context on the urgency of completing this before next Tuesday? Is it tied to an announcement on Discourse or another critical timeline?

If we opt for (a), and it aligns with the timing of our last board meeting, I'm available over the next few days, including the weekend, if needed, to accommodate scheduling.

2024-04-03 21:48 UTC, RaitoBezarius commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
> While I agree with the approach of passing the core aspects of the policy first and addressing other points subsequently, I share a concern regarding potential loss of momentum if we delay resolution on certain elements.

I may be wrong, but my feeling is that we are not going to run out of momentum given the intensity of the engagement, though we will exhaust ourselves by trying to get agreement on everything right now and this will cause instantaneous disengagement, more on that in the next paragraph.

> Could you provide further context on the urgency of completing this before next Tuesday? Is it tied to an announcement on Discourse or another critical timeline?

Yes, the longer we delay passing at least a first "policy" even incomplete in terms of the exact details, the more people are tired out / burned out and are leaving the project, at the time of speaking, we lost another person who is handling a significant part of operations in nixpkgs over dismissive comments like https://github.com/NixOS/foundation/pull/128#issuecomment-2035356976.

My personal priority is to get the community in a working state again before we end up losing so much that nixpkgs is set back for years.

> If we opt for (a), and it aligns with the timing of our last board meeting, I'm available over the next few days, including the weekend, if needed, to accommodate scheduling.

cc @Janik-Haag @piegamesde @tomberek @paperdigits as the folks who were vocal on the ongoing discussion, I believe.
Let's create tentatively a slot for that meeting, please use: https://meet.dgnum.eu/ to create a scheduling.

2024-04-04 03:14 UTC, djacu commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
> > 
> 
> I may be wrong, but my feeling is that we are not going to run out of momentum given the intensity of the engagement, though we will exhaust ourselves by trying to get agreement on everything right now and this will cause instantaneous disengagement, more on that in the next paragraph.

That's true. I didn't mention it in my previous comment but the other thing to consider is burn out.

2024-04-04 03:22 UTC, djacu commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
> Let's create tentatively a slot for that meeting, please use: https://meet.dgnum.eu/ to create a scheduling.

I've started an instance here with my availability.
https://meet.dgnum.eu/nix-policy-discussion-874929

@Janik-Haag @piegamesde @tomberek @paperdigits

2024-04-04 03:28 UTC, djacu commented
> This is extremely unusual from everything I've seen at industry conferences, and the one time I recall it happening (over in the Elixir community) we still make fun of everybody involved in that decision and the awkwardness it caused.

@crertel I tried finding something related to this in the Elixir forms but was fruitless in my efforts. If this was documented somewhere, or if there is anything in the Elixir docs related to governance or policy, please share.

2024-04-04 10:28 UTC, piegamesde commented on Sponsorship.md
> +    2. Selection Committee members shall be notified at least 2 weeks prior to the event and provided with at least 1 week to submit objections to the Foundation Board via email.
> So if a person in the community who is not part of selection committee wants to weigh in on a sponsor or potential sponsor, how would that be done?

They can't because sponsorships will unlikely to be known until finalized. I initially proposed to have the proposals open for community discussion in some form, however this was rejected

2024-04-04 13:13 UTC, crertel commented
> @crertel I tried finding something related to this in the Elixir forms but was fruitless in my efforts. If this was documented somewhere, or if there is anything in the Elixir docs related to governance or policy, please share.

It's oral history, and I'm not interested in airing out old drama with strangers--the main point being, it's weird to tell people at a conference they can't rep their employers if they want to.

If that's not good enough (and I wouldn't blame you), it should be sufficient to see other industry and event precedent: what other industry and community events use this proposed policy of controlling their attendees' visible affiliation?

2024-04-04 15:41 UTC, RaitoBezarius commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
@piegamesde won't be able to attend from what I understand.

2024-04-04 15:54 UTC, RaitoBezarius commented
For information, I will take a proactive posture here to moderate the off-topic, outdated, abusive comments in this PR. We are focusing on getting a sponsorship policy off, concerns about whether a sponsorship policy makes sense can be done once, but once it is starting to run into circles, I will hide them.

Whether the moderation team or not is not representative of the community is another debate that has not its place in this PR, consider pushing proposals that encompass a condition that the selection committee is *representative* of the community in its decision-making, but let's not open all the debate at the same time, or we will not converge.

Dismissive comments are not tolerated anymore, and I will strongly moderate them, I include comments that disparage entities without proof, including:

- power grab fantasies
- reasoning about the perceived size of an entity to decide whether it makes sense to do proactive policymaking
- discussions that do not acknowledge the effective impact of the absence of sponsorship policy on the various operations of our community, e.g. nixpkgs

In addition, I will mention that what other communities does is, at some point, of limited usefulness to us. We have *this* community and not the community of other projects, it's up to the leadership of a project to answer with policies that make sense for *their* community, not to tell to community members that others do it like this, and therefore we must follow the "global ambient culture". If you disagree with this, please provide constructive elements to enable comparisons, otherwise, I will deem such comments offtopic too.

Again, I deeply apologize for the tone, but I will be rigorous to give everyone a chance to participate into this without being drained and dropping out of the discussion needlessly. This is not to say that those discussions cannot take place, but this might not be the right tool / right place to have such debates.

2024-04-04 18:15 UTC, piegamesde commented
> they have somewhat more work if a lot of controversy is expressed on the various forums they moderate. But that's just part of the moderation job -- it's not really "high stakes" and it's not a good basis for making decisions

Let's be frank: If the moderation team were paid even something remotely reasonable for its job, the additional work of the fallout from the NixCon NA sponsorship would have been *more expensive than the sponsorship money we got from Anduril*.

I really really wish this was only "somewhat more work". But it's not. I wish the moderation team was in a better position, but in the last year the new recruitments have been barely sufficient to keep up with the burnout rate.

2024-04-04 20:21 UTC, crertel commented
> Dismissive comments are not tolerated anymore, and I will strongly moderate them, I include comments that disparage entities without proof, including:
>    power grab fantasies
>    reasoning about the perceived size of an entity to decide whether it makes sense to do proactive policymaking
>    discussions that do not acknowledge the effective impact of the absence of sponsorship policy on the various operations of our community, e.g. nixpkgs

This is dismissing core, important issues.

* **Re: power grab.** The proposed changes would give the moderation team (currently, to my knowledge, the most vocal group) veto power. This power did not previously exist, and to my knowledge there is not a reciprocal veto power on moderation team activities. Even if you do not wish to classify this as a power grab, the core question remains: *should the moderation team have this veto power*?

* **Re: scale.** Proactive policymaking has a cost--as you and others keep pointing out, we apparently care about the cost to the moderation team, so apparently cost is a factor. Smaller orgs have a smaller cost budget than larger orgs. Similarly, smaller orgs have a smaller blast radius when things _do_ go wrong, as can be seen in the difference between a PR gaffe between myself, my employer, and one of our vendors (say, AWS). If we want to talk about how damaging bad PR is--e.g., talk about the blast radius--it makes sense to take into account how large the org is. It's a valid area of discussion to check cost vs benefits.

* **Re: prior work by other communities.** If I recall reading correctly, a lot of this discussion and its context [uses other communities, notably the ASF, as a touchstone](https://github.com/NixOS/foundation/issues/110). In addition, if nobody else has a policy about not wearing silly hats, maybe that's a valid data point that a policy about not wearing silly hats is _maybe not that important_. Dismissing prior art here seems rather arbitrary.

* **Re: discussions that do not acknowledge the effective impact of the absence of sponsorship policy on the various operations of our community, e.g. nixpkgs**. Nixpkgs [seems to be doing just fine](https://github.com/NixOS/nixpkgs/pulls). Can you enumerate the exact concerns, bullet-point style, of how lacking this policy hurts nixpkgs? I suspect the answer is (given other comments here) "it makes moderation harder". Okay, how important is that? Is the comfort of moderators more important than all other concerns (because again, that's what the proposed language implements with the veto setup)?  Maybe it is, maybe it isn't, but that's a topical discussion worth having.

2024-04-04 20:35 UTC, RaitoBezarius commented
> > Dismissive comments are not tolerated anymore, and I will strongly moderate them, I include comments that disparage entities without proof, including:
> > power grab fantasies
> > reasoning about the perceived size of an entity to decide whether it makes sense to do proactive policymaking
> > discussions that do not acknowledge the effective impact of the absence of sponsorship policy on the various operations of our community, e.g. nixpkgs
> 
> This is dismissing core, important issues.

Thank you for improving your prose on the matters you care about.

> * **Re: power grab.** The proposed changes would give the moderation team (currently, to my knowledge, the most vocal group) veto power. This power did not previously exist, and to my knowledge there is not a reciprocal veto power on moderation team activities. Even if you do not wish to classify this as a power grab, the core question remains: _should the moderation team have this veto power_?

I am a project team lead of NixCon, the answer is yes. If folks want to organize conferences and find out that the moderation team having this veto power is excessive, we can revisit. This decision does not enshrine the moderation team as some sort of unchangeable god.

I hope this is clear enough and we don't enter into a debate on that, I am not interested into that.

> * **Re: scale.** Proactive policymaking has a cost--as you and others keep pointing out, we apparently care about the cost to the moderation team, so apparently cost is a factor. Smaller orgs have a smaller cost budget than larger orgs. Similarly, smaller orgs have a smaller blast radius when things _do_ go wrong, as can be seen in the difference between a PR gaffe between myself, my employer, and one of our vendors (say, AWS). If we want to talk about how damaging bad PR is--e.g., talk about the blast radius--it makes sense to take into account how large the org is. It's a valid area of discussion to check cost vs benefits.

Yes, I am a project team lead of NixCon and a board observer of the NixOS Foundation and a quite active community member.

I can tell you that the cost of not doing that is devastating for most of my operations that were ongoing before the event: we lost weeks of work of many individuals whose time is extremely expensive and valuable.

You can measure it quite easily by reviewing all the reactions over the situation over social media, Discourse, GitHub, Matrix, Discord and any platform. If you dismiss this and say 'this is not a big deal', I'm afraid we cannot come to a mutual understanding of the concept of cost and I think there's no further conversation to have over this matter.

> * **Re: prior work by other communities.** If I recall reading correctly, a lot of this discussion and its context [uses other communities, notably the ASF, as a touchstone](https://github.com/NixOS/foundation/issues/110). In addition, if nobody else has a policy about not wearing silly hats, maybe that's a valid data point that a policy about not wearing silly hats is _maybe not that important_. Dismissing prior art here seems rather arbitrary.

Yes, those policies were used for starters, and they created this situation, so what you are saying is you want the community to accept the policies of other communities and this is dismissive of our community.

I don't think we are in the business to force communities to agree to our views.

> * **Re: discussions that do not acknowledge the effective impact of the absence of sponsorship policy on the various operations of our community, e.g. nixpkgs**. Nixpkgs [seems to be doing just fine](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc). Can you enumerate the exact concerns, bullet-point style, of how lacking this policy hurts nixpkgs? I suspect the answer is (given other comments here) "it makes moderation harder". Okay, how important is that? Is the comfort of moderators more important than all other concerns (because again, that's what the proposed language implements with the veto setup)?  Maybe it is, maybe it isn't, but that's a topical discussion worth having.

As you don't seem to be a contributor, I suppose you are not aware of what's going on, I will put it shortly like this: long term trusted community members who are critical to our operations are quitting the project over this situation and the lack of swift decisionmaking from our side. You cannot know that, you are not participating into this part of the community, but from my PoV, this part of the community is critical and justify why we are going about this like this.

If everyone who is not engaging into Nixpkgs operations on a daily basis will come and ask to rehash everything that's going on, that's not tractable, I will ask that folks who don't know, don't interact that much, to step aside and leave the space for people who are actively working directly on the project. Otherwise, you are wasting time of others, as time is of essence here.

2024-04-04 20:59 UTC, crertel commented
>  the lack of swift decisionmaking from our side. 

If the concern is swift decisionmaking, the earlier suggested language of this PR--having the Board make a vote--seems to be the faster thing (consensus happens faster with `n=1`). If the problem is the Board not doing its job quickly enough, I'm unsure that this solves for that.

> dismissive of our community.

If you limit community to the people you engage with on social media, then yes I am not a member of the community. If you include people who have been running Nix quietly in production for users for years, and who was first introduced to Nix (the language) around 2011, then yes I'm a member of the community. Consider me part of the "dark matter" of Nix developers--and if that isn't good enough to be considered part of the community, that's unfortunate but doesn't impact my servers.


> If folks want to organize conferences and find out that the moderation team having this veto power is excessive, we can revisit. 

Seems simpler to go with the faster approach originally in the PR, and add the moderation team veto in _if_ it turns out to be a problem.

> long term trusted community members who are critical to our operations are quitting the project over this situation and 

It's unclear if you mean "our" (the moderation team) or "our" (the folks involved in making sure I can still pull from the repo and so forth in a more general sense). I understand your alarm and concern _for your team_, if that's been a problem.

2024-04-04 21:05 UTC, RaitoBezarius commented
> > the lack of swift decisionmaking from our side.
> 
> If the concern is swift decisionmaking, the earlier suggested language of this PR--having the Board make a vote--seems to be the faster thing (consensus happens faster with `n=1`). If the problem is the Board not doing its job quickly enough, I'm unsure that this solves for that.

Right, unfortunately, we can only do what we can with what we have.

> 
> > dismissive of our community.
> 
> If you limit community to the people you engage with on social media, then yes I am not a member of the community. If you include people who have been running Nix quietly in production for users for years, and who was first introduced to Nix (the language) around 2011, then yes I'm a member of the community. Consider me part of the "dark matter" of Nix developers--and if that isn't good enough to be considered part of the community, that's unfortunate but doesn't impact my servers.

Yeah, so, I wouldn't say that I limit community to that. I am very happy you are running NixOS in production, but, unfortunately, in the project, I have to work with the people who are affected and care about things. If this doesn't impact your servers or yourself, I would like to ask you to let people who are affected to express themselves or to be representative of such folks.

> 
> > If folks want to organize conferences and find out that the moderation team having this veto power is excessive, we can revisit.
> 
> Seems simpler to go with the faster approach originally in the PR, and add the moderation team veto in _if_ it turns out to be a problem.

So following this reasoning, we should include the moderation team veto _now_ because this policy is not really far from the prior informal in existent policy and proved to be a problem. Happy we came finally to an agreement.

> 
> > long term trusted community members who are critical to our operations are quitting the project over this situation and
> 
> It's unclear if you mean "our" (the moderation team) or "our" (the folks involved in making sure I can still pull from the repo and so forth in a more general sense). I understand your alarm and concern _for your team_, if that's been a problem.

I am not part of the moderation team, "our" refers to operations of the whole NixOS project, that includes the build infrastructure team for example who lost two members over this situation. But that's not limited to it, there's plenty of people who are maintaining stuff who are throwing the towel. We can pull repo today, whether we will be able to continue to maintain the complicated nixpkgs machinery in six months is questioned here.

2024-04-05 01:47 UTC, numinit commented
> I can tell you that the cost of not doing that is devastating for most of my operations that were ongoing before the event: we lost weeks of work of many individuals whose time is extremely expensive and valuable.

> You can measure it quite easily by reviewing all the reactions over the situation over social media, Discourse, GitHub, Matrix, Discord and any platform. If you dismiss this and say 'this is not a big deal', I'm afraid we cannot come to a mutual understanding of the concept of cost and I think there's no further conversation to have over this matter..

Conflating social media reaction with the moderation team's desired representation of the community is a mistake. It's important to be clear: while community representation is important, setting a precedent for those who yell the loudest on social media getting their way can easily be abused by starting an internet mob in order to gain more representation through social pressure. People know this tactic works. And, as we have seen, this results in a lot of yelling over each other and division, and is hard to moderate.

> Yes, those policies were used for starters, and they created this situation, so what you are saying is you want the community to accept the policies of other communities and this is dismissive of our community.

I think we need to be clear about what created the situation: no policy to start for NixCon EU, and a policy that many thought inadequately addressed the problem thereafter for NixCon NA. Now, it's clear we need some sort of policy, and everyone who feels slighted now wants it to be _their_ policy.

----

As a frequent contributor to nixpkgs, I have not really loved how these discussions have gone for quite some time, and dislike what seems like the community yelling over each other, dueling via public open letters, squabbling about each others' perceived differences in morality, and the entire thing generally turning certain sections of the Discourse and Github into a corrosive mess. Everyone's trying to grab the steering wheel for a problem that will never be adjudicated with satisfaction to everyone, and I much prefer contributing to nixpkgs over expending more words on this stuff...

So, to build some consensus, my only recommendation is for the project to pick its battles:

- If the policy is too complex by including a bunch of hidden vetoes, rules that come down to differences in opinion (mostly, the ones that have been squabbled over), and opportunities for backhandedness, we'll lose more trust and drag this out for longer. **If something is empirically being squabbled over excessively, maybe it's best just left out.**
- If any team _needs_ representation, that's fine if and only if how it's done removes all scope for manipulation. Transparent decision-making processes and a policy that establishes clear process will help. **People just yelling about the issue or shutting each other down because of differences in opinion should not hinder decision-makers being neutral.**
- We should set expectations that not everyone will get their way. **Compromise doesn't have to come at the expense of trust. See the two previous points.**
- And...  **just be kind to each other, this whole thing is a pain and doesn't need to be nearly this contentious.**

I'm grabbing a beer, logging off for tonight, and installing NixOS on a fanless i7 SBC router I'm setting up... :smiley:

2024-04-05 11:28 UTC, RaitoBezarius commented
> > I can tell you that the cost of not doing that is devastating for most of my operations that were ongoing before the event: we lost weeks of work of many individuals whose time is extremely expensive and valuable.
> 
> > You can measure it quite easily by reviewing all the reactions over the situation over social media, Discourse, GitHub, Matrix, Discord and any platform. If you dismiss this and say 'this is not a big deal', I'm afraid we cannot come to a mutual understanding of the concept of cost and I think there's no further conversation to have over this matter..
> 
> Conflating social media reaction with the moderation team's desired representation of the community is a mistake. It's important to be clear: while community representation is important, setting a precedent for those who yell the loudest on social media getting their way can easily be abused by starting an internet mob in order to gain more representation through social pressure. People know this tactic works. And, as we have seen, this results in a lot of yelling over each other and division, and is hard to moderate.

Correct, though, this is unrelated and missing the point.

> > Yes, those policies were used for starters, and they created this situation, so what you are saying is you want the community to accept the policies of other communities and this is dismissive of our community.
> 
> I think we need to be clear about what created the situation: no policy to start for NixCon EU, and a policy that many thought inadequately addressed the problem thereafter for NixCon NA. Now, it's clear we need some sort of policy, and everyone who feels slighted now wants it to be _their_ policy.

Correct, you are just rehashing what everyone has been saying in the past. The important criterion is whether a policy would have fixed the situation for NixCon EU & NixCon NA. Whether folks want _their_ policy or not is of little interest to me. What I care about is whether this is an effective policy to address community concerns and get everyone back to productive work.

> As a frequent contributor to nixpkgs, I have not really loved how these discussions have gone for quite some time, and dislike what seems like the community yelling over each other, dueling via public open letters, squabbling about each others' perceived differences in morality, and the entire thing generally turning certain sections of the Discourse and Github into a corrosive mess. Everyone's trying to grab the steering wheel for a problem that will never be adjudicated with satisfaction to everyone, and I much prefer contributing to nixpkgs over expending more words on this stuff...

Sure, we all are in the same boat, but those discussions are of political nature and are important. Somefew *have* to take care of them.

> So, to build some consensus, my only recommendation is for the project to pick its battles:
> 
> * If the policy is too complex by including a bunch of hidden vetoes, rules that come down to differences in opinion (mostly, the ones that have been squabbled over), and opportunities for backhandedness, we'll lose more trust and drag this out for longer. **If something is empirically being squabbled over excessively, maybe it's best just left out.**
> * If any team _needs_ representation, that's fine if and only if how it's done removes all scope for manipulation. Transparent decision-making processes and a policy that establishes clear process will help. **People just yelling about the issue or shutting each other down because of differences in opinion should not hinder decision-makers being neutral.**
> * We should set expectations that not everyone will get their way. **Compromise doesn't have to come at the expense of trust. See the two previous points.**
> * And...  **just be kind to each other, this whole thing is a pain and doesn't need to be nearly this contentious.**

I am sorry, I fail to understand your recommendations, you are hinting at a mix of things and I cannot see the relation between your words and the current state of things.
From my PoV, this is not actionable, but thank you for your input.

2024-04-05 13:46 UTC, numinit commented
Let me be _very_ clear, then, and explicitly spell it out: You are likely losing contributors because a lot of the discussion is toxic and people are failing to compromise. This is being egged on by the people who are supposed to be in charge, yourself included, who are not actually discussing things in a way that facilitates compromise. I'm providing actionable ways for people to come to compromise, including recommending setting expectations that not everyone will get their way. So, responding to that with:

> Sure, we all are in the same boat, but those discussions are of political nature and are important. Somefew have to take care of them.

Completely disregards that a discussion can be of "political nature" and not just people yelling past each other.

And:

> I am sorry, I fail to understand your recommendations, you are hinting at a mix of things and I cannot see the relation between your words and the current state of things.

This is a major reason the discussion has turned toxic. Here's a concrete example:

[Responding to newcomers with](https://github.com/NixOS/foundation/pull/128#issuecomment-2038163123) shutting _entire responses_ down:

> I hope this is clear enough and we don't enter into a debate on that, I am not interested into that.

> Otherwise, you are wasting time of others, as time is of essence here.

> I wouldn't expect a newcomer to come and try to give us lessons about how we do such a thing, I do not recommend doing this or engaging into this.

And, then [twisting words](https://github.com/NixOS/foundation/pull/128#issuecomment-2038219421):

> Happy we came finally to an agreement.

is a concrete reason that this discussion is toxic.

2024-04-05 14:06 UTC, RaitoBezarius commented
> Let me be _very_ clear, then, and explicitly spell it out: You are likely losing contributors because a lot of the discussion is toxic and people are failing to compromise. This is being egged on by the people who are supposed to be in charge, yourself included, who are not actually discussing things in a way that facilitates compromise. I'm providing actionable ways for people to come to compromise, including recommending setting expectations that not everyone will get their way. So, responding to that with:
> 
> > Sure, we all are in the same boat, but those discussions are of political nature and are important. Somefew have to take care of them.
> 
> Completely disregards that a discussion can be of "political nature" and not just people yelling past each other.

I fail to understand what constitute 'people yelling past each other' vs. 'a discussion of political nature'.

> And:
> 
> > I am sorry, I fail to understand your recommendations, you are hinting at a mix of things and I cannot see the relation between your words and the current state of things.
> 
> This is a major reason the discussion has turned toxic. Here's a concrete example:
> 
> [Responding to newcomers with](https://github.com/NixOS/foundation/pull/128#issuecomment-2038163123) shutting _entire responses_ down:
> 
> > I hope this is clear enough and we don't enter into a debate on that, I am not interested into that.
> 
> > Otherwise, you are wasting time of others, as time is of essence here.
> 
> > I wouldn't expect a newcomer to come and try to give us lessons about how we do such a thing, I do not recommend doing this or engaging into this.
> 
> And, then [twisting words](https://github.com/NixOS/foundation/pull/128#issuecomment-2038219421):
> 
> > Happy we came finally to an agreement.
> 
> is a concrete reason that this discussion is toxic.

OK, I am sorry you think the discussion is toxic.

Unfortunately, I will make it clear again, newcomers doesn't have a lot of useful inputs to add here except if they're experts on the subject (sponsorship policies, open source governance models, etc.) because they don't have the full context to comment on the topic without forcing everyone else to rehash the context for them. This makes the discussion extremely draining for people with the context who want to move forward on the points we need to compromise on.

Does this create the risk of losing contributors over this discussion? Yes. Do I want that? No. Am I forced to answer those messages? Yes.

Nevertheless, everyone is free to observe this discussion and decide what they want to do with their free time. If you are not affected, if you are not a stakeholder of that discussion, please consider **NOT** chiming into that discussion to let folks who **are affected**, who **are stakeholder of that discussion** drive this discussion.

The contributors we are losing right now are contributors who are explicitly (:= this is what they told me) tired of your answers, the answers of newcomers who have no idea of what's going on in this community.

I don't know who are 'the contributors' you are mentioning in your header, I don't know if they are maintainer of the critical packages of nixpkgs, I don't know if they are newcomers who would become contributors. But again, as I said, this is not actionable to me. Feel free to contact me in private if you want to add more to this that you do not want to share publicly, my DMs/emails and anything and everything are always open.

I cannot make it simpler than that, if this is not possible to understand, I will moderate systematically until we get to this point. This is my last warning on the offtopic discourse.

---

Either:

- react to actionable items to make the sponsorship policy move forward
- start a new topic about _current_ moderation team position in the community
- start a new topic about what should be the moderation team in the future in the community

2024-04-05 14:10 UTC, RaitoBezarius commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
@djacu @paperdigits @tomberek @Janik-Haag 7, April 2024 at 7PM CEST: https://files.lahfa.xyz/sponsorship-discussion.ics for the Calendar invite.

2024-04-05 14:12 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/community-calendar/18589/130

2024-04-05 16:00 UTC, Jaculabilis commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
As a compromise between the efficiency of fewer decisionmakers and slimmer processes, and the acknowledged stake that Moderation and Marketing have in the outcome of sponsorship, here's an idea:

```suggestion
    1. The Selection Committee is composed of the event organizers and the Foundation Board.

    2. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email.

    3. The Selection Committee shall be notified at least 2 weeks prior to the event and provided with at least 1 week to submit objections to committee members in written form.

    4. The Selection Committee should consider objections that are specific to the sponsor and relevant to the NixOS mission, consulting with the Marketing team and the Moderation team as necessary.

    5. Either the event organizers or the Foundation board may decline the sponsor.
```

My basic reasoning here is that we should trust the Foundation Board to consult the people who may be impacted and use their veto power on their behalf. If we didn't think the Foundation would act in the best interests of Nix, we might as well pack up our bags, because what would the point of any of this be after that?

2024-04-05 16:12 UTC, RaitoBezarius commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
We already have tried this, this resulted in the current situation. The Foundation board has many things to do, this is about giving a mandate to the people who are the closest to the community to handle this.

The Foundation act in the best interests of Nix by delegating this to the group that also aact in the best interests of Nix, for example.

2024-04-05 18:03 UTC, AshleyYakeley commented
I would like to point out that the current PR is a huge improvement over having no policy. It clearly empowers both event organisers to decline sponsorships that they believe are locally unpopular, and the board to decline sponsorships that they believe would be detrimental to the larger community, where this wasn't clear before.

> The important criterion is whether a policy would have fixed the situation for NixCon EU & NixCon NA.

Trying to guarantee a single particular outcome, especially for a past event, is a bad approach to making policy. Ask yourself, if the moderation team happened to be very pro-Anduril, as is perfectly possible in the future, would you still want to make this change?

2024-04-05 18:06 UTC, AshleyYakeley commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
The moderation team is not "the closest to the community".

2024-04-05 18:08 UTC, RaitoBezarius commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
Can you cite another set of contributors who are well positioned to make those calls?

2024-04-05 18:15 UTC, RaitoBezarius commented
> > The important criterion is whether a policy would have fixed the situation for NixCon EU & NixCon NA.
> 
> Trying to guarantee a single particular outcome, especially for a past event, is a bad approach to making policy. Ask yourself, if the moderation team happened to be very pro-Anduril, as is perfectly possible in the future, would you still want to make this change?

If the moderation team was pro-Anduril in its actions, nixpkgs would be defunct.

I wonder why is this so hard to understand given all those reactions from contributors of large ecosystem in nixpkgs who form a network of even larger contributors of signifcant subsystems of nixpkgs.

I wonder also if the motivations of certain individuals here is to force a fork of nixpkgs to the detriment of the community or if this is just a benign misunderstanding of not being someone who contribute and interact on a daily basis with nixpkgs developers.

2024-04-05 19:08 UTC, AshleyYakeley commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
The board is best positioned to make these kinds of executive decisions. That's their job.

2024-04-05 19:19 UTC, AshleyYakeley commented
Nobody is going to fork nixpkgs.

2024-04-05 19:37 UTC, paperdigits commented
> Nobody is going to fork nixpkgs.

Please, let's try not to be so flippant. We're in this situation because what was in/not in place previously didn't work. Now we're trying to find a way forward.

> If the moderation team was pro-Anduril in its actions, nixpkgs would be defunct.

This feels a little bit too dramatic of a statement. Perhaps the team would sustain a substantial workload hit, but nixpkgs itself, the code base, would still be around. 

> I wonder also if the motivations of certain individuals here is to force a fork of nixpkgs to the detriment of the community or if this is just a benign misunderstanding of not being someone who contribute and interact on a daily basis with nixpkgs developers.

I don't think we should take the conversation down this path. I understand your frustrations @RaitoBezarius 

I think that in the interest of compromise and moving forward, that in Sunday's meeting we should work to agree and codify that the process (1) needs the formation of a selection committee and (2) the selection committee should include a community representation component. Once we agree on this, then we can take on defining the composition of the selection committee.

2024-04-05 22:45 UTC, tomberek commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
That looks like it is more accurate as well. The earlier one is a bit over-specific on the details in policy regime where we don't generally have that much formal procedure.

2024-04-06 14:54 UTC, RaitoBezarius commented
> > If the moderation team was pro-Anduril in its actions, nixpkgs would be defunct.
> 
> This feels a little bit too dramatic of a statement. Perhaps the team would sustain a substantial workload hit, but nixpkgs itself, the code base, would still be around.

What value is there for a nixpkgs that does not receive the sheer amount of free work from the people who have been clearly against the sponsorship? Yes, sure, the repo would still exist. Then, you can count how many days / weeks you are left before you cannot make it work anymore, be it for infrastructure reasons or maintenance reasons.

Yes, we can have a nixpkgs without those people, but I should remind everyone to try to understand what makes nixpkgs magic and what constitute its value.

> While Andruil is the past, its quite easy to imagine other future scenarios where people's current feelings might be flipped. If there is a NixCon in Iran or Russia or another non-Western country where a government contractor or other business is using nix but their output is objectionable.
> 
> For me personally, this boils down to the problem of contributing to the commons, which is problematic, but still the best idea we have. The more contribution to the commons there is, the better off we are. Even where we disagree with some entity's output, understanding their use of the commons enriches the commons itself.
> 
> My own fear, and the reason why I've taken the time to try and contribute to this conversation, is because I would not want to find the Con I attend to be canceled or not be able to afford a venue because a sponsor has been rejected. I appreciate and am envious that our European counterparts have the possibility of finding a large scale venue that'll host a con for little or no cost, but that isn't a reality here in America and probably other places around the world.

I think you are conflating two things.

(a) Letting everyone contributing to the commons: this is not what we were discussing here.
(b) Making conference happen and possible to attend in expensive places of the world, respectfully of the community: This is the matter.

In (b), you are conflating two things again.

(a) Making a conference possible requires a target budget A
(b) Accepting as many sponsorships as possible

I will remind that I was involved with the past NixCon and I came to NixCon NA. Given our current state of popularity, I do not believe there's any trouble to have (a) even if we don't do (b). (I am even involved into looking into NixCon Asia, so...)

Thus, I think your fear of not having any conference at all is only but a fear.

Assuming that we would _have_ a problem, conference in place A or B requires more money than usual, this is a board matter to see if we can use the money of successful NixCon to help other NixCon to flourish, for example.

Of course, sometimes thing does not pan out as desired / expected, but this is hardly related to whether we have to offend the whole community by accepting a sponsor for a meager small K of dollars.

> > I wonder also if the motivations of certain individuals here is to force a fork of nixpkgs to the detriment of the community or if this is just a benign misunderstanding of not being someone who contribute and interact on a daily basis with nixpkgs developers.
> 
> I don't think we should take the conversation down this path. I understand your frustrations @RaitoBezarius

I don't think too, but I think we are having too many interactions from people who are not grasping the situation we are in. Nonetheless, people who are watching this issue and us and who are grasping the situation are unamused and are losing hope or being significantly affected by seeing folks spreading out dismissive comments while they are in `NixOS/*`, `nix-community/*`, working and trusting us to do the right thing and represent their opinion adequately.

So when I see so much out-of-touch participation, I can only wonder if I am being subjected to interactions of the same nature as https://lwn.net/ml/debian-vote/CA+f80t5gKqVHwDPLw9wHSUdWNkysN8mdoH+f-e34LSYTtk6Okw@mail.gmail.com/ here.

> I think that in the interest of compromise and moving forward, that in Sunday's meeting we should work to agree and codify that the process (1) needs the formation of a selection committee and (2) the selection committee should include a community representation component. Once we agree on this, then we can take on defining the composition of the selection committee.

I think we already agreed on (1), (2), I believe we need to discuss the composition of the selection committee on Sunday's meeting as per the PR thread that sparked the meeting. If we need to roll back (1) & (2), I feel like we are taking a ton of step backward every time we are trying to move forward, and this is not a good sign.

2024-04-06 18:37 UTC, AshleyYakeley commented
> What value is there for a nixpkgs that does not receive the sheer amount of free work from the people who have been clearly against the sponsorship? Yes, sure, the repo would still exist. Then, you can count how many days / weeks you are left before you cannot make it work anymore, be it for infrastructure reasons or maintenance reasons.

This isn't going to happen. For example, nobody threatened to stop their free work in the open letter, because it would be obviously non-credible and come across as petulant. I don't know why people think I'm being flippant in making this point.

If another conference is sponsored by a controversial company, be it Raytheon, Monsanto, RJ Reynolds, OnlyFans, etc., some people will not attend, and some speakers will withdraw. The current draft of the PR empowers local organisers to weigh the value of the sponsorship with the loss of participation, and for the board to do the same at a community-wide level. I very much doubt Anduril, specifically, would make the cut at this point.

2024-04-06 18:57 UTC, lf- commented
> This isn't going to happen. For example, nobody threatened to stop their free work in the open letter, because it would be obviously non-credible and come across as petulant. I don't know why people think I'm being flippant in making this point.

Two major members of NixOS infra team are currently on strike until this is resolved in a satisfactory way. There is a strong likelihood of there not *being* any 24.05 release because there's no committers who aren't on strike who would be release managers. Some committers who are on the moderation team can't help with releasing the software because they're too busy wasting their time dealing with bad-faith trolls on threads related to this issue and overall increase in background trolling as of late. 

Currently the project is at its knees because of the foundation not resolving the issue of advertising for companies actively involved in imperialism and, some, in the genocide in Gaza. I'm not interested in discussing whether any particular companies are in either of those positions. The point here is that the foundation isn't listening to the most active contributors and they're suffering the consequences thereof (several tens of thousands of dollars of very much non-fungible labour withheld, significantly more than the sponsorships in question).

2024-04-06 22:05 UTC, paperdigits commented
> I think you are conflating two things.
> 
> (a) Letting everyone contributing to the commons: this is not what we were discussing here. (b) Making conference happen and possible to attend in expensive places of the world, respectfully of the community: This is the matter.

In my view, bringing people together at events *is* enriching the commons, which is why I brought it up. 

> In (b), you are conflating two things again.
> 
> (a) Making a conference possible requires a target budget A (b) Accepting as many sponsorships as possible

Please note that I *did not* say anything about accepting as many sponsors as possible. Rather my concern was specifically the opposite: if we have so few sponsors that rejecting one makes the conference not financially possible.

It seems we've only wanted to discuss things that have already happened & how not to find ourselves in that situation again, but I feel strongly that policy needs to be forward looking as well.

2024-04-06 22:19 UTC, mweinelt commented
> my concern was specifically the opposite: if we have so few sponsors that rejecting one makes the conference not financially possible.

Thanks for worrying out about, but I can tell you as a NixCon 2023 organizer, that this fear is unfounded.

We had [15 sponsors](https://2023.nixcon.org/#sponsors) and excluding the one sponsor did not make a dent in the budget. The NixCon 2022 [sponsor section](http://2022.nixcon.org/#sponsors) also doesn't look like it lacked sponsors.

2024-04-06 22:28 UTC, mweinelt commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
> The board is best positioned to make these kinds of executive decisions. That's their job.

The board is stuffed with people who have [commercial interest](https://github.com/NixOS/foundation?tab=readme-ov-file#board-affiliation-transparency) in Nix/Nixpkgs/NixOS. You believing they are  “closest to the community” reveals you to be an outsider to this community.

2024-04-06 23:31 UTC, paperdigits commented
> Thanks for worrying about that, but I can tell you as a NixCon 2023 organizer, that this fear is unfounded.

Again, I'd ask that the comments not be so flippant. Sponsors of the past are not necessarily sponsors of the future. Are we so stuck looking backward right now that what's head isn't even in sight?

> Weigh the cost of offending contributors versus the small monetary gain.

It's not just the "small monetary gain," its about having a policy that is acceptable for the next thousand contributors, and the thousand after that; that is what I mean by "forward looking." Unless we're planning to revisit this often, we should try and make policy that works for a longer period of time.

2024-04-08 04:26 UTC, tomberek approved these changes
As agreed with representatives on 2024-04-07.

2024-04-08 08:29 UTC, JulienMalka commented on Sponsorship.md
> +    - 2 representatives from the event organizers
```suggestion
    - 2 representatives from the event organizers, including 1 member of the NixCon PL team if the PL team is engaging on the event
```

2024-04-08 08:32 UTC, JulienMalka commented on Sponsorship.md
> +    The sponsor will be accepted if a strong majority of the committee votes to accept the sponsor.
```suggestion
    The sponsor will be accepted if a strong majority (at least 4 votes in favor) of the committee in reached to accept the sponsor.
```

2024-04-08 08:37 UTC, JulienMalka requested changes
We are missing the concept that the moderation seat is supposed to ensure minorities of the community are correctly represented, and that failing that, this policy is deemed void.
As that was discussed yesterday.

2024-04-08 09:22 UTC, zimbatm commented on Sponsorship.md
> +    - 2 representatives from the event organizers
One issue raised is that the PL team isn't officially defined yet (even if it exists and is doing a great job).

To solve this and move forward, I proposed creating a second document that establishes the PL team. As part of it, the PL team gets one of the event organizers' votes on all the events they are responsible for.

2024-04-08 09:29 UTC, RaitoBezarius commented on Sponsorship.md
> +    - 2 representatives from the event organizers
What do you think of this informal post and definition (I must assume) https://discourse.nixos.org/t/governance-through-project-leads-in-nixcon-2024/33981 ? What should be improved to make it more defined ?

2024-04-08 09:36 UTC, edolstra commented
The sponsor rules as currently proposed by this PR seem reasonable to me:

> 1. Sponsors must be individuals or organizations that are legally able to operate in compliance with the laws and policies of their own origin, that of the NixOS Foundation, and of relevant third-party agreements.

since this is a non-discriminatory policy that doesn't exclude entire industries. 

However, it's important to acknowledge that this policy *does* permit sponsorship by defense contractors, which is what triggered the current controversy. So the big question is whether committee members can reject sponsors on grounds not listed in the policy. (The proposal does mention a requirement to state "reasons why the sponsorship would impede the NixOS mission", but that's pretty vague, lacking a stated "NixOS mission".) If in practice the policy is "the ethics/politics of the committee members", then that's not a very transparent policy. Ideally it should be clear in advance to potential sponsors whether they're welcome.

2024-04-08 09:42 UTC, JulienMalka commented
> The sponsor rules as *currently* proposed by this PR seem reasonable to me

Just want to clarify/reiterate that the current state of this PR does not reflect the agreements that was found yesterday after countless hours of negotiation.   

> So the big question is whether committee members can reject sponsors on grounds not listed in the policy. 

The committee members can reject sponsors on grounds not explicitly listed, yes.

2024-04-08 13:25 UTC, jonringer commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
> The board is stuffed with people who have [commercial interest](https://github.com/NixOS/foundation?tab=readme-ov-file#board-affiliation-transparency) in Nix/Nixpkgs/NixOS

Although true, I would also say that would be conjunction with massive community legacy:
- Eelco Dolstra: The creator of Nix, 20+ years of contributions
- Théophane Hufschmitt: Contributor of 5+ years, member of Nix maintenance team
- Jonas Chevalier: Contributor of ~9+ years, pillar of the community, creator of Direnv.
- Domen (recently left): Contributor of 10+ years, ~6x NixOS release manager. Creator of Cachix.
- Ron Efroni - Sadly not personally familiar with him. Only one without a large Nix legacy.

2024-04-08 13:30 UTC, jonringer commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
I think "the board is stuffed pillars of the community and also want to see Nix be a commercial success" is a better way to phrase that.

2024-04-08 13:31 UTC, mweinelt commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
There is no question they have had a big influence on the community in the past, but nowadays, they rarely interact with or contribute to nixpkgs anymore. But that is precisely where the largest part of the community interaction actually happens.

If you're not there you're likely missing out on a lot of people that keep nixpkgs running. And it is exactly those people who are in need of representation here.

2024-04-08 16:12 UTC, djacu commented on Sponsorship.md
> +    1. The Sponsor Chair will submit sponsorship proposals to the Selection Committee via email, composed of the event organizers and the Foundation Board.
I believe this is resolved as of yesterday's call.

2024-04-08 16:14 UTC, djacu commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
I believe this is resolved as of yesterday's call.

2024-04-08 16:14 UTC, djacu commented on Sponsorship.md
> +Nonetheless, the Foundation retains the right to decline sponsorship through a Board vote in cases where it would impede the Foundation's mission.
I believe this is resolved as of yesterday's call.

2024-04-08 16:56 UTC, djacu commented on Sponsorship.md
> +    The sponsor will be accepted if a strong majority of the committee votes to accept the sponsor.
Pushed a couple updates. One to use more precision language and one to address this. We good?

2024-04-08 17:10 UTC, JulienMalka commented on Sponsorship.md
> +    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
I want the language to be about committee members and not expressed votes. I'm fine if we say something like "A sponsor will be accepted if and only if 70% or more of committee members are in favor."

2024-04-08 17:15 UTC, JulienMalka commented on Sponsorship.md
> +    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
I don't see why we don't keep the clear "4/5 members should be in favor". When we revisit the committee composition, we have to revisit this document anyway.

2024-04-08 17:16 UTC, JulienMalka commented on Sponsorship.md
> +    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
```suggestion
    A sponsor will be accepted if and only if at least 4 members of the committee are in favor.
```

2024-04-08 17:16 UTC, djacu commented on Sponsorship.md
> +    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
@JulienMalka I'm not sure what is missing. What you have suggested is pretty close to the current language is it not? Or are you just stating what you would like to see and not making a suggestion?

2024-04-08 17:18 UTC, djacu commented on Sponsorship.md
> +    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
> @JulienMalka I'm not sure what is missing. What you have suggested is pretty close to the current language is it not? Or are you just stating what you would like to see and not making a suggestion?

Ah sorry your second and third comment hadn't loaded yet when I commented. All clear now

2024-04-08 17:21 UTC, JulienMalka commented on Sponsorship.md
> +    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
> @JulienMalka I'm not sure what is missing. What you have suggested is pretty close to the current language is it not? Or are you just stating what you would like to see and not making a suggestion?

1) The `if and only if` makes it clear that the only way for a sponsors to get approved is through the committee agreement. It's important.
2) I want the language to be clear that we need a majority of members and not voters (abstention counts as a no). It's also important.
3) I think that 4/5 is more clear than 70% but I can compromise on that.

2024-04-08 17:27 UTC, djacu commented on Sponsorship.md
> +    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
To preserve the understanding of what a "significant/strong/super" majority is in the future, how about the following?

```suggestion
    4. In the event of an impasse during deliberation, objections shall be put to a vote.
    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
    With the current composition of the selection committee, acceptance necessitates at least 4 members in favor.
```

2024-04-08 17:27 UTC, djacu commented on Sponsorship.md
> +    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
To preserve the understanding of what a "significant/strong/super" majority is in the future, how about the following?

```suggestion
    4. In the event of an impasse during deliberation, objections shall be put to a vote.
    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
    With the current composition of the selection committee, acceptance necessitates at least 4 members in favor.
```

2024-04-08 17:33 UTC, JulienMalka commented on Sponsorship.md
> +    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
Can we change `70% of the committee votes` to `70% of the committee members` ? And for the rest no strong opinion on adding or not the last sentence.

2024-04-08 17:43 UTC, djacu commented on Sponsorship.md
> +    A sponsor will be accepted if a significant majority, defined as greater than 70% of the committee votes, is in favor of acceptance.
> Can we change `70% of the committee votes` to `70% of the committee members` ? And for the rest no strong opinion on adding or not the last sentence.

Ah I understand what you were trying to convey now. Members not votes. Yeah that's better.

2024-04-08 18:03 UTC, zimbatm commented on Sponsorship.md
> +    - 2 representatives from the event organizers
I like it overall. It does a good job of defining the scope, the roles and responsibilities, the team composition, and how to contact you.

One unclear point was the distinction between Bootstrap PL and PL, as well as the mechanisms around it. Are the PLs the event organizers for a specific year? This must be better defined before it can be referenced in this document.

Another aspect could be to officially assign the NixCon brand and assets to the PL. In that scenario, the foundation wouldn't even have to be involved creating this very policy, as the PL would be empowered to write it themselves.

Then give the team a homepage, move this to a founding document, done.

2024-04-08 21:14 UTC, jonringer commented on Sponsorship.md
> +        2. A majority (>50%) of the Foundation Board vote to decline the sponsor.
I agree, nixpkgs is usually the gateway drug. And it's a "choose your own adventure" from there. I would still consider work on NixOS/nix as contributions though.

Grahamc was Mr. Infra + Mr. moderation + Mr. ofBorg for many year. I would still consider his contributions to be just as valuable as well. <3 you @grahamc. Glad his hats were distributed amongst many.

2024-04-08 21:36 UTC, RaitoBezarius commented on Sponsorship.md
> +    - 2 representatives from the event organizers
Here we go. https://github.com/NixOS/foundation/pull/134

2024-04-09 08:03 UTC, zimbatm commented on Sponsorship.md
> +    - 2 representatives from the event organizers
Ok, we can work on this separately then, and resolve this thread.

Don't forget to add this notion in the other document: that the PL team would take one vote of the events team.

2024-04-09 08:45 UTC, mweinelt commented on Sponsorship.md
> +    - 2 representatives from the event organizers
Including this here would IMO be the sensible thing to do, given that this was the compromise that led to the agreement on the call.

2024-04-09 08:58 UTC, JulienMalka commented on Sponsorship.md
> +    - 2 representatives from the event organizers
No mention of the PL team in the sponsorship policy is a deal-breaker for me.

2024-04-10 10:26 UTC, zimbatm commented
We have now integrated the remaining changes in #136, which I believe is very close to the consensus we reached on Sunday. For more context, please also read the [discourse post](https://discourse.nixos.org/t/nixos-foundation-event-sponsorship-policy/43110). Thanks again for all your feedback, effort and patience.

2024-04-10 10:26 UTC, closed without merging