policies: add Code of Conduct policy
NixOS/foundation pull request #44
Opened 2023-03-10 14:11 UTC by zimbatm

2023-03-11 08:48 UTC, domenkozar approved these changes

2024-03-15 09:44 UTC, piegamesde commented
Text looks pretty good to me, only thing I'd add is a short reference to the general Code of Conduct we do have now.

2024-04-11 05:21 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/is-there-a-policy-for-removing-foundation-members-or-what-is-considered-acceptable-behavior/43159/2

2024-04-11 06:15 UTC, thufschmitt approved these changes
Mh apologies, I thought I had approved this long ago.

But here it is then

2024-04-11 23:49 UTC, Janik-Haag requested changes
This looks quite good to me except for one major thing: I would replace shall with must in most points. The US Government has quiet a nice page explaining the difference: https://www.plainlanguage.gov/guidelines/conversational/shall-and-must/

2026-06-09 15:46 UTC, closed without merging